master:
  adminUser: "admin"
  adminPassword: "admin1234"
  resources:
    limits:
      cpu: "1500m"
      memory: "1024Mi"
  serviceType: NodePort
  nodePort: 32377

persistence:
  storageClass: "managed-nfs-storage"
  accessMode: "ReadWriteOnce"
  size: "10Gi"

rbac:
  create: true

  