master:
  adminUser: "admin"
  adminPassword: "admin1234"
  resources:
    limits:
      cpu: "1500m"
      memory: "1024Mi"
  serviceType: NodePort
  nodePort: 32377

JCasC:
    enabled: true
    PluginVersion: 1.36
    ConfigScripts: |
      welcome-message:
        jenkins:
          systemMessage: Welcome Gabo!

persistence:
  storageClass: "managed-nfs-storage"
  accessMode: "ReadWriteOnce"
  size: "10Gi"

rbac:
  create: true

  