# Use echo -n "" | base64 to create encoded value
# for examle echo -n "R00t" | base64
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-pass           
  namespace: full-stack-app
type: Opaque
data:
  password: UjAwdA==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass           
  namespace: full-stack-app
type: Opaque
data:
  username: Y2FsbGljb2Rlcg==
  password: Y0BsbDFjMGQzcg==
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-url           
  namespace: full-stack-app
type: Opaque
data:
  database: cG9sbHM=
  url: amRiYzpteXNxbDovL3BvbGxpbmctYXBwLW15c3FsOjMzMDYvcG9sbHM/dXNlU1NMPWZhbHNlJnNlcnZlclRpbWV6b25lPVVUQyZ1c2VMZWdhY3lEYXRldGltZUNvZGU9ZmFsc2U=